server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_manager_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # pour mettre à jour le schéma automatiquement
    show-sql: true # Affiche les requêtes SQL dans la console
    properties:
      hibernate:
        format_sql: true # Formatte les requêtes SQL pour une meilleure lisibilité
  flyway:
    enabled: true # Active Flyway pour la gestion des migrations
    locations: classpath:db/migration # Dossier des fichiers de migration
  security:
    user:
      name: admin # Identifiant par défaut de Spring Security
      password: admin # Mot de passe par défaut
  swagger-ui:
    path: /swagger-ui.html # Accès à la documentation Swagger

logging:
  level:
    root: INFO # Niveau de log par défaut
    org.springframework.security: DEBUG # Active les logs de Spring
